In [112]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [113]:
# load dataset
df = pd.read_csv('tested.csv')

In [114]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [115]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [116]:
df['Age'] = df['Age'].fillna(df['Age'].mean())

In [117]:
df['Fare'] = df['Fare'].fillna(df['Fare'].mean())

In [118]:
x = df[['Pclass','Age','Sex','Fare']]
y = df['Survived']

In [119]:
from sklearn.preprocessing import LabelEncoder

In [120]:
le = LabelEncoder()
x['Sex'] = le.fit_transform(x['Sex'])

In [121]:
x

     Pclass       Age  Sex      Fare
0         3  34.50000    1    7.8292
1         3  47.00000    0    7.0000
2         2  62.00000    1    9.6875
3         3  27.00000    1    8.6625
4         3  22.00000    0   12.2875
..      ...       ...  ...       ...
413       3  30.27259    1    8.0500
414       1  39.00000    0  108.9000
415       3  38.50000    1    7.2500
416       3  30.27259    1    8.0500
417       3  30.27259    1   22.3583

[418 rows x 4 columns]

In [122]:
y

0      0
1      1
2      0
3      0
4      1
      ..
413    0
414    1
415    0
416    0
417    0
Name: Survived, Length: 418, dtype: int64

In [123]:
from sklearn.model_selection import train_test_split

In [124]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=42)

In [125]:
from sklearn.preprocessing import StandardScaler

In [126]:
std =StandardScaler()

In [127]:
x_train_scaled = std.fit_transform(x_train)
x_train_scaled

array([[-1.47596812,  0.38989079,  0.78310898,  0.60029624],
       [ 0.8727114 , -0.04584013,  0.78310898, -0.51006323],
       [-1.47596812,  2.44400174, -1.27696148,  3.01110083],
       ...,
       [-1.47596812,  1.15067262,  0.78310898,  0.60029624],
       [-0.30162836, -0.52304742,  0.78310898, -0.41546542],
       [ 0.8727114 , -0.04584013,  0.78310898, -0.51006323]],
      shape=(292, 4))

In [128]:
x_test_scaled = std.transform(x_test)
x_test_scaled

array([[ 0.8727114 , -0.44696923,  0.78310898, -0.51863133],
       [-1.47596812,  0.61812534, -1.27696148,  2.83931615],
       [ 0.8727114 , -0.75128197,  0.78310898, -0.51006323],
       [ 0.8727114 ,  0.3138126 ,  0.78310898, -0.50766456],
       [ 0.8727114 ,  0.38989079, -1.27696148, -0.4371275 ],
       [-0.30162836,  1.45498536,  0.78310898, -0.20981801],
       [ 0.8727114 , -0.1426565 , -1.27696148, -0.50718417],
       [-1.47596812,  1.37890717,  0.78310898, -0.20981801],
       [-0.30162836, -0.90343833, -1.27696148, -0.42369132],
       [ 0.8727114 , -0.04584013,  0.78310898, -0.5051277 ],
       [ 0.8727114 , -0.75128197,  0.78310898, -0.24025383],
       [-1.47596812,  1.53106354, -1.27696148,  0.01063601],
       [ 0.8727114 , -1.13167288, -1.27696148, -0.49744964],
       [-1.47596812,  0.61812534, -1.27696148,  1.15403562],
       [ 0.8727114 , -0.04584013,  0.78310898, -0.5051277 ],
       [ 0.8727114 , -0.04584013,  0.78310898,  0.29189257],
       [ 0.8727114 , -0.21873468, -1.27696148, -0.50965194],
       [-1.47596812,  1.83537628,  0.78310898,  0.18502502],
       [ 0.8727114 , -1.58814199,  0.78310898, -0.15840616],
       [-0.30162836, -0.5991256 ,  0.78310898, -0.4648208 ],
       [-0.30162836,  1.98753264,  0.78310898, -0.42369132],
       [-1.47596812,  0.7702817 ,  0.78310898,  0.21566648],
       [ 0.8727114 , -2.12068927, -1.27696148, -0.41094118],
       [-0.30162836, -0.06657831,  0.78310898, -0.42369132],
       [ 0.8727114 , -0.04584013, -1.27696148, -0.38674388],
       [ 0.8727114 , -0.94147743, -1.27696148, -0.51774128],
       [-1.47596812, -0.44696923, -1.27696148,  0.27455074],
       [-1.47596812, -0.04584013,  0.78310898, -0.20076953],
       [ 0.8727114 ,  0.61812534,  0.78310898, -0.51863133],
       [-0.30162836, -0.06657831,  0.78310898, -0.42369132],
       [ 0.8727114 ,  0.08557805,  0.78310898, -0.26698799],
       [ 0.8727114 , -0.67520378, -1.27696148,  0.0153659 ],
       [-1.47596812,  0.16165624, -1.27696148,  1.85570458],
       [ 0.8727114 , -0.04584013,  0.78310898, -0.5051277 ],
       [-0.30162836, -0.67520378, -1.27696148, -0.4648208 ],
       [-0.30162836, -0.44696923,  0.78310898, -0.4648208 ],
       [ 0.8727114 , -0.52304742, -1.27696148, -0.51006323],
       [-0.30162836, -0.04584013,  0.78310898, -0.39003424],
       [-0.30162836, -0.1426565 , -1.27696148, -0.20981801],
       [-1.47596812,  0.12361714,  0.78310898,  2.84198956],
       [ 0.8727114 , -0.52304742, -1.27696148, -0.51006323],
       [ 0.8727114 , -0.04584013, -1.27696148, -0.25177008],
       [-0.30162836,  0.7702817 ,  0.78310898, -0.39003424],
       [-1.47596812, -0.04584013,  0.78310898,  0.01392637],
       [-1.47596812, -0.18069559,  0.78310898, -0.18150777],
       [ 0.8727114 , -0.75128197,  0.78310898, -0.50834896],
       [ 0.8727114 , -0.04584013, -1.27696148,  0.50665757],
       [-0.30162836, -0.52304742, -1.27696148, -0.18150777],
       [-1.47596812,  1.83537628, -1.27696148, -0.21475355],
       [ 0.8727114 ,  0.38989079,  0.78310898, -0.51828913],
       [ 0.8727114 ,  0.27577351,  0.78310898, -0.50876025],
       [ 0.8727114 ,  1.07459444, -1.27696148, -0.51870042],
       [ 0.8727114 , -0.04584013, -1.27696148, -0.5051277 ],
       [-0.30162836,  1.22675081,  0.78310898, -0.4648208 ],
       [-0.30162836, -0.1426565 ,  0.78310898, -0.40957075],
       [-0.30162836, -0.82736015, -1.27696148, -0.20981801],
       [ 0.8727114 , -0.04584013,  0.78310898, -0.5051277 ],
       [-0.30162836, -0.37089105,  0.78310898, -0.42369132],
       [ 0.8727114 , -2.33599053, -1.27696148, -0.29906899],
       [ 0.8727114 , -0.52304742,  0.78310898, -0.51828913],
       [ 0.8727114 ,  1.45498536,  0.78310898, -0.39901363],
       [-0.30162836, -0.75128197,  0.78310898, -0.44836901],
       [-1.47596812, -0.04584013, -1.27696148, -0.18150777],
       [-0.30162836,  0.69420352,  0.78310898, -0.20981801],
       [-0.30162836, -1.20775107, -1.27696148,  0.00405529],
       [-0.30162836, -0.44696923,  0.78310898, -0.4648208 ],
       [ 0.8727114 ,  0.7702817 ,  0.78310898, -0.50841805],
       [ 0.8727114 , -0.52304742,  0.78310898, -0.51335359],
       [-1.47596812,  0.61812534,  0.78310898, -0.14894638],
       [-1.47596812,  0.92243807,  0.78310898, -0.18150777],
       [-1.47596812,  1.98753264,  0.78310898,  1.77296523],
       [-0.30162836, -0.06657831,  0.78310898, -0.29207698],
       [ 0.8727114 ,  0.08557805,  0.78310898, -0.5128732 ],
       [-1.47596812, -0.04584013, -1.27696148, -0.11631754],
       [-1.47596812,  1.07459444,  0.78310898, -0.14894638],
       [ 0.8727114 , -0.67520378, -1.27696148, -0.49505097],
       [-1.47596812, -0.06657831,  0.78310898, -0.20981801],
       [ 0.8727114 , -0.67520378, -1.27696148, -0.40888471],
       [ 0.8727114 , -0.37089105, -1.27696148, -0.27521389],
       [ 0.8727114 , -0.44696923,  0.78310898, -0.51170841],
       [ 0.8727114 , -0.67520378,  0.78310898, -0.50930974],
       [-1.47596812,  1.30282899, -1.27696148,  3.67897453],
       [ 0.8727114 , -0.75128197,  0.78310898, -0.51870042],
       [ 0.8727114 , -0.97951652, -1.27696148, -0.50793766],
       [-0.30162836,  0.08557805,  0.78310898, -0.42369132],
       [-0.30162836, -0.52304742,  0.78310898, -0.11933315],
       [-0.30162836, -0.04584013,  0.78310898, -0.46139389],
       [-1.47596812, -0.52304742,  0.78310898,  0.71587008],
       [-0.30162836, -0.90343833,  0.78310898, -0.4648208 ],
       [ 0.8727114 , -0.04584013,  0.78310898, -0.52157949],
       [-1.47596812, -0.44696923,  0.78310898, -0.20981801],
       [ 0.8727114 , -1.89245472,  0.78310898, -0.29084309],
       [-1.47596812,  1.15067262,  0.78310898,  0.66541737],
       [ 0.8727114 , -1.28382925,  0.78310898, -0.48579684],
       [ 0.8727114 , -0.44696923,  0.78310898, -0.50718417],
       [ 0.8727114 , -1.58814199, -1.27696148,  0.13402446],
       [ 0.8727114 ,  0.00949987,  0.78310898, -0.34143236],
       [-1.47596812, -1.0555947 ,  0.78310898,  0.13731482],
       [ 0.8727114 , -0.04584013,  0.78310898, -0.51006323],
       [-0.30162836,  0.3138126 ,  0.78310898, -0.43438499],
       [ 0.8727114 , -0.52304742,  0.78310898, -0.50965194],
       [ 0.8727114 , -0.04584013,  0.78310898, -0.51006323],
       [ 0.8727114 , -0.5991256 ,  0.78310898, -0.52157949],
       [ 0.8727114 , -0.29481287,  0.78310898, -0.49505097],
       [ 0.8727114 , -0.29481287, -1.27696148, -0.50718417],
       [ 0.8727114 , -0.04584013, -1.27696148, -0.21859175],
       [ 0.8727114 , -1.0555947 ,  0.78310898, -0.50766456],
       [-0.30162836, -0.5991256 ,  0.78310898, -0.4648208 ],
       [ 0.8727114 , -0.04584013,  0.78310898, -0.51870042],
       [ 0.8727114 , -0.67520378, -1.27696148, -0.51047453],
       [ 0.8727114 , -0.04584013,  0.78310898, -0.50766456],
       [-0.30162836,  2.29184538,  0.78310898, -0.43438499],
       [ 0.8727114 , -1.47402471,  0.78310898, -0.39901363],
       [-1.47596812, -0.04584013,  0.78310898, -0.63756463],
       [-1.47596812, -1.89245472,  0.78310898,  1.57520151],
       [ 0.8727114 , -0.04584013,  0.78310898, -0.53165621],
       [-1.47596812, -0.67520378, -1.27696148,  0.38210433],
       [-0.30162836, -0.37089105,  0.78310898, -0.16046263],
       [-0.30162836, -2.27893189, -1.27696148, -0.18102738],
       [-0.30162836, -0.67520378, -1.27696148, -0.29207698],
       [ 0.8727114 , -0.04584013,  0.78310898, -0.49422838],
       [-0.30162836, -0.29481287,  0.78310898, -0.20981801],
       [ 0.8727114 , -0.97951652,  0.78310898, -0.49505097],
       [ 0.8727114 , -0.04584013,  0.78310898, -0.28090292],
       [ 0.8727114 ,  0.16165624,  0.78310898, -0.50834896],
       [-1.47596812, -0.5991256 ,  0.78310898,  0.90067801]])

In [129]:
from sklearn.svm import SVC

In [130]:
model = SVC()

In [131]:
parameters = {
    'kernel': ['linear', 'poly', 'rbf', 'sigmoid']
    
}

In [132]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV

In [133]:
classifier = GridSearchCV(model,parameters,cv=5)
classifier.fit(x_train_scaled,y_train)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'kernel': ['linear', 'poly', 'rbf', 'sigmoid']})

In [134]:
classifier.best_params_

{'kernel': 'linear'}

In [135]:
model.fit(x_train_scaled,y_train)

SVC()

In [136]:
y_pred = model.predict(x_test_scaled)

In [137]:
from sklearn.metrics import accuracy_score

In [138]:
print(f"accuracy score:{accuracy_score(y_pred,y_test)}")

accuracy score:1.0